# №1. Тензоры в `torch`

In [1]:
import torch

In [17]:
print(f"{torch.__version__=}")
print(f"{torch.version.cuda=}")
print(f"{torch.cuda.is_available()=}")
# print(f"{torch.cuda.get_device_name(0)=}") # AssertionError: Torch not compiled with CUDA enabled

torch.__version__='2.8.0+cpu'
torch.version.cuda=None
torch.cuda.is_available()=False


In [2]:
"""
torch.tensor() <--> numpy.array()
"""

'\ntorch.tensor() <--> numpy.array()\n'

In [4]:
[
torch.tensor([1, 2, 3]),
torch.tensor([1, 2, 3], dtype=torch.float32), 
torch.tensor([1, 2, 3], dtype=torch.int32),
]

[tensor([1, 2, 3]), tensor([1., 2., 3.]), tensor([1, 2, 3], dtype=torch.int32)]

In [6]:
torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)

tensor([1., 2., 3.], requires_grad=True)

In [7]:
torch.tensor([1, 2, 3], requires_grad=True)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [19]:
try:
    torch.tensor([1, 2, 3], requires_grad=True, device=torch.device("cuda:0"))
except AssertionError as e:
    print(e)

Torch not compiled with CUDA enabled


In [20]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(f"{t.dtype=}")
print(f"{t.shape=}")
print(f"{t.size()=}")
print(f"{t.ndim=}")
print(f"{t.numel()=}")

t.dtype=torch.float32
t.shape=torch.Size([2, 3])
t.size()=torch.Size([2, 3])
t.ndim=2
t.numel()=6


In [22]:
t[0,0], t[0,0].item()

(tensor(1.), 1.0)

In [ ]:
torch.zeros([3,4], dtype=torch.float32) # и др. функции как в numpy

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
t1 = torch.zeros([3,4], dtype=torch.float32)
t2 = torch.ones([3,4], dtype=torch.float32) * 5
t3 = t1 + t2

In [32]:
t3.sum().item(), t3.mean().item()

(60.0, 5.0)

In [ ]:
t3, t3.view([4,3]) # reshape

(tensor([[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]]),
 tensor([[5., 5., 5.],
         [5., 5., 5.],
         [5., 5., 5.],
         [5., 5., 5.]]))

In [40]:
[t,
t.mean(dim=1),
t.mean(dim=1, keepdim=True)]

[tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([2., 5.]),
 tensor([[2.],
         [5.]])]

In [48]:
# CPU <--> GPU
print(f"{torch.cpu.is_available()=}")
print(f"{torch.cuda.is_available()=}")

torch.cpu.is_available()=True
torch.cuda.is_available()=False


In [ ]:
t = t.cpu()
t = t.to('cpu')
# t = t.cuda()
device = 'cuda' if torch.cuda.is_available() else 'cpu'
t = t.to(device).detach() # тупа копирует тензор (на самом деле открепляет градиент (что бы это ни значило))
t.device

device(type='cpu')

In [ ]:
# Для вычислений тензора должны быть на одном устройстве (оба на CPU или оба на GPU)
# CUDA - технология NVIDIA для работы с GPU, AMD - ROCm (офф. на Linux, плохо на Windows)