# №11. **BatchNorm**. Ускорение и стабильность обучения

1. https://habr.com/ru/articles/309302
2. https://habr.com/ru/companies/mvideo/articles/782360
3. ...

## 1. Краткая теория

**Batch Normalization (BN)** предназначен для улучшения скорости, производительности и стабильности обучения нейронных сетей.

При использовании **BatchNorm** сохраняется пространственная структура выходных данных, т.е. нормализация не влияет на пространственное расположение признаков.

В некоторых случаях **BN** может служить регуляризатором, уменьшая необходимость в **Dropout**.

## 2. Использование в `torch`

In [1]:
import torch
import torch.nn as nn

In [23]:
model = nn.Sequential(
    nn.Linear(3, 5, bias=False), # отключение bias
    nn.ReLU(),
    nn.BatchNorm1d(5), # BN до или после функции активации
    nn.Linear(5, 4)
)

In [24]:
x = torch.rand([2, 3])
x

tensor([[0.6436, 0.9802, 0.4771],
        [0.6353, 0.4780, 0.1326]])

In [25]:
model.eval()
model(x)

tensor([[-0.0406, -0.4081, -0.3633, -0.1883],
        [-0.0813, -0.3200, -0.4015, -0.1202]], grad_fn=<AddmmBackward0>)

In [26]:
model.train()
model(x)

tensor([[ 0.0810, -0.4843, -0.3236, -0.4041],
        [-0.4370, -0.2133, -0.4635,  0.5785]], grad_fn=<AddmmBackward0>)

## 3. Итоги

***Использование Batch Normalization***
<table>
  <tr>
    <th>Минусы</th>
    <th>Плюcы</th>
  </tr>
  <tr>
    <td><img src="data/my_images/BN_disadv.png" width="350"></td>
    <td><img src="data/my_images/BN_adv.png" width="350"></td>
  </tr>
</table>